url: https://craigchamberlain.it
baseurl: /

# Site settings
title: Craig Chamberlain - IT Services
email: craig.chamberlain11@gmail.com
phone: +1 07526 825 153
description: "IT Support, Training and Advice for Home & Business. Personal and professional service in your own home or office."


# Team names, titles and social links
people:
- name: Craig Chamberlain
  pic: 1
  position: Owner
  social:
    - title: twitter
      url: https://twitter.com/hagatorn
    - title: linkedin
      url: https://www.linkedin.com/in/craig-chamberlain-61037149
    - title: stack-overflow
      url: https://stackoverflow.com/users/3822155/craig-c

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: pinterest
    url: https://www.pinterest.co.uk/craigchamberlainit
  - title: facebook
    url: https://www.facebook.com/CraigChamberlainIT/

# Postal address (add as many lines as necessary)
address:
  - line: Sedbergh, UK

# Build settings
markdown: kramdown
permalink: pretty
